@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Final state

package AddressBook {
    class State1 as "<u>Robert:Person</u>"
}

@end
