@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Initial state

package AddressBook {
    class State1 as "<u>John:Person</u>"
    class State2 as "<u>James:Person</u>"
    class State3 as "<u>Peter:Person</u>"
    class State4 as "<u>Luke:Person</u>"
    class State5 as "<u>Simon:Person</u>"
}


@end
