@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start

:User executes delete 1 3 5;
:DeleteCommandParser;
if () then ([else])
  :Sort indexes ascendingly;
  :DeleteCommand#execute;
  if () then ([else])
    :Proceed to next stage of DeleteCommand#execute;
  else ([Index greater than size of address book || Not a positive integer])
  endif
else ([Duplicates Present || Invalid Index]);
endif

stop

@enduml
