@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start

:User enters 'find n/John Alice';
:Input passed into AddressBookParser#parse;
:Call FindCommandParser#parse;
:Call FindNameCommandParser#parse;
  if () then ([Argument is valid])
    :Return new FindNameCommand object;
    :Call FindNameCommand#execute;
    :Call Model#updateFilteredPersonList;
    :Success message + contacts listed;
  else ([else])
    :Invalid command format + error message shown;
  endif

stop
@enduml
