@startuml
hide circle
skinparam classAttributeIconSize 0

Class "<<interface>>\nParser" as Parser
Class RiskProfileCommandParser {
  +parse(): RiskProfileCommand
}
Class ParseException

RiskProfileCommandParser .up.|> Parser
Parser .right.> ParseException: throws >
RiskProfileCommandParser .right.> ParseException: throws >
@enduml
