!pragma DPI 600
@startuml
!define LOGIC_COLOR_T1 #LightBlue
!define MODEL_COLOR_T1 #LightGreen

skinparam sequence {
    ArrowFontStyle plain
    ParticipantFontSize 18
    LifeLineBorderColor #666666
}

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR_T1
participant ":RiskProfileCommandParser" as RiskProfileCommandParser LOGIC_COLOR_T1
participant ":RiskProfileCommand" as RiskProfileCommand LOGIC_COLOR_T1
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR_T1
participant ":AddressBook" as AddressBook MODEL_COLOR_T1
end box

User -> LogicManager: riskprofile 7 res/a,b,c,d,e,e,b,c
activate LogicManager

LogicManager -> RiskProfileCommandParser: parse()
activate RiskProfileCommandParser

create RiskProfileCommand
RiskProfileCommandParser  -> RiskProfileCommand
activate RiskProfileCommand

RiskProfileCommand--> RiskProfileCommandParser
deactivate RiskProfileCommand

LogicManager -> RiskProfileCommand : execute()
activate RiskProfileCommand

RiskProfileCommand -> Model: retrieve person at index 7
activate Model
Model -> AddressBook: getPerson(7)
activate AddressBook
AddressBook --> Model: Person
deactivate AddressBook
Model --> RiskProfileCommand: Person
deactivate Model

RiskProfileCommand -> RiskProfileCommand: calculate risk level()
RiskProfileCommand -> Model: set new risk profile
activate Model
Model -> AddressBook: updateFilteredPersonList()
activate AddressBook
AddressBook --> Model: updated AddressBook
deactivate AddressBook
Model --> LogicManager: updated Model
deactivate Model
deactivate RiskProfileCommand
deactivate RiskProfileCommandParser

LogicManager --> User: result
deactivate LogicManager
@enduml
